config/routes.rb
Rails.application.routes.draw do
  resources :bugs
  resources :projects
  resources :users
  resources :sessions
  root  'users#home'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new",  :as => "login"
  get "signup" => "users#new",   :as => "signup"
  match '/view_projects',         to: 'projects#view_projects', via: 'get'
  match '/view_developers',       to: 'users#view_developers', via: 'get'
  match '/view_qa_list',           to: 'users#view_qa_list', via: 'get'
  match '/details',                to: 'users#details', via: 'get'
  match '/view_qa_projects/:id',   to: 'users#view_qa_projects', 
  as:'view_qa_projects', via: 'get'

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user, foreign_key: "assigned_to"
	has_many :bugs

	belongs_to :manager, class_name: 'User', foreign_key: 'created_by'
	validates :project_name,length: { minimum: 2 }, presence: true
	validates :assigned_to, presence: true
	#validates_uniqueness_of :project_name

	self.per_page = 5
end
WillPaginate.per_page = 5

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects =  Project.paginate(page: params[:page],:per_page => 5)

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @users = User.where(:user_type => "qa")
  end

  # GET /projects/1/edit
  def edit
  end

  # def view_projects
  #   @projects = Project.all
  # end


  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  helper_method:view_projects 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :assigned_to, :created_by)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="signup">
  <%= form_for(@project) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :project_name, class: "control-label" %><br>
    <%= f.text_field :project_name, class: "form-control", :required => true %>
  </div>

  <div class="field">
     <label>Assigned To:</label>
        <%= f.select(:assigned_to ,options_from_collection_for_select(@users, :id, :name), { prompt: 'Select Option' },:required => true) %>
  </div>
 
  <div class="field">
    <%= f.label :created_by, class: "control-label" %><br>
  <%= f.number_field :created_by, :value => current_user.id %>
 </div>

  <div class="actions">
    <%= f.submit "Create New Project", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>
<%= link_to 'Back', projects_path,{:style=>'color:#0000FF;font-size:20px'}  %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/home.html.erb
<h1>Manage Your Projects here </h1>

<%= link_to "View all Projects", logout_path %>

app/views/projects/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Listing Projects</h1>
<%= will_paginate @projects, :page_links => false %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Project name</th>
      <th>Assigned to</th>
      <th>Created by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <% @projects.each do |project| %>
       
      <tr>  
        <td><%= project.project_name %></td>
        <td><%= project.user.try(:name) %></td>

        <td><%= project.created_by %></td>
        <td><%= link_to 'Show', project %>  
        </td> 
         <!-- <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
      <% end %>
   
  </tbody>
</table>
<%= will_paginate %>
<br>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="projectshow">
	<p id="notice"><%= notice %></p>

<p class = "paraClass">
  <strong>Project name:</strong>
  <%= @project.project_name %>
</p>

<p class = "paraClass">
  <strong>Assigned to:</strong>
  <%= @project.user.try(:name) %>
</p>

<p class = "paraClass">
  <strong>Created by:</strong>
  <%= @project.created_by %>
</p>

 
<%= link_to 'Back', projects_path,{:style=>'color:#0000FF;font-size:20px'}  %>
</div>