config/routes.rb
Rails.application.routes.draw do
  resources :bugs
  resources :projects
  resources :users
  resources :sessions
  root  'users#home'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new",  :as => "login"
  get "signup" => "users#new",   :as => "signup"
  match '/view_projects',         to: 'projects#view_projects', via: 'get'
  match '/view_developers',       to: 'users#view_developers', via: 'get'
  match '/view_qa_list',           to: 'users#view_qa_list', via: 'get'
  match '/details',                to: 'users#details', via: 'get'
  match '/view_qa_projects/:id',   to: 'users#view_qa_projects', 
  as:'view_qa_projects', via: 'get'

end

app/models/bug.rb
class Bug < ActiveRecord::Base
	belongs_to :project

	belongs_to :user, foreign_key: "assigned_to"
	
	has_attached_file :image

	validates_attachment :image,
	  :content_type => { :content_type => "image/png" },
	  :size => { :in => 0..100.kilobytes }

  validates :title,length: { minimum: 2 }, presence: true

  #validates_uniqueness_of :title
 self.per_page = 5
end
WillPaginate.per_page = 5

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    if(current_user.user_type == "developer")
      @bugs = current_user.bugs.paginate(page: params[:page],:per_page => 5)
    else
    @bugs = Bug.all.paginate(page: params[:page],:per_page => 5)
  
    end
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
    @projects = Project.all  
    @users = User.where(:user_type => "developer")
  
  end

  # GET /bugs/1/edit
  def edit
        @users = User.where(:user_type => "developer")
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)
    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description,
       :deadline, :image, :bug_type, :status, :assigned_to, :project_id)
    end
end

app/helpers/bugs_helper.rb
module BugsHelper
	def bug_options
		 [ ["Bug", 'bug'], ["Feature", 'feature'] ]
	end

	def bug_status_options
	  [ ["New", 'new'], ["Started", 'started'], ["Resolved", 'resolved'] ]
	end

	def feature_status_options
	  [ ["New", 'new'], ["Started", 'started'], ["Completed", 'completed'] ]
	end
 # <%= f.select :status, options_for_select(feature_status_options,:selected => @bug.status), { prompt: 'Select status' }%>
# <%= f.select :status, options_for_select(bug_status_options,:selected => @bug.status), { prompt: 'Select status' }%>
end

app/views/bugs/_form.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="signup">
  <%= form_for(@bug) do |f| %>
   <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title, class: "control-label" %><br>
    <%= f.text_field :title, class: "form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description , class: "form-control", :required => true%>
  </div>

   <div class="field">
     <label>Project Name:</label><br>
      <%= f.select(:project_id ,options_from_collection_for_select(@projects, :id, :project_name), :required => true)%>
  </div>

  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline , :required => true%>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :bug_type %><br>
    <%= f.select :bug_type, options_for_select(bug_options), { prompt: 'Select type' },
    :onchange => "myfunction();", :required => true %>
  </div>

<% if current_user.user_type != "manager" %>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select([[]]), { prompt: 'Select status' }
     %>
  </div>
  <%end%>


  <% if current_user.user_type == "qa" %>
   <div class="field">
     <label>Assigned To:</label>
        <%= f.select(:assigned_to ,options_from_collection_for_select(@users, :id, :name)) %>

  </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', bugs_path,{:style=>'color:#0000FF;font-size:20px'}  %>


 </div>

app/views/bugs/_form_dev.html.erb
<div class="signup">
  <%= form_for(@bug) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :title , class: "control-label" %><br>
    <%= @bug.title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= @bug.description %>
  </div>

   <div class="field">
     <label>Project Name:</label><br>
      <%= @bug.project.project_name %>
  </div>

  <div class="field">
    <%= f.label :deadline %><br>
    <%= @bug.deadline %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= image_tag(@bug.image.url, :style => "border: 1px solid grey;max-width:80px;") %>
   <!--  <%= f.file_field :image %>
  </div> -->
  <div class="field">
     <p style="font-size: 20px;margin-top: 15px">
    <strong>Bug type:</strong>
    <% if @bug.bug_type == "bug" %>
      Bug
    <%  else %>
      Feature
    <% end %>
  </p>
  </div>

<% if current_user.user_type != "manager" %>
  <div class="field">
    <%= f.label :status %><br>
    <% if @bug.bug_type == "bug" %>
    <%= f.select :status, options_for_select(bug_status_options,:selected => @bug.status), { prompt: 'Select status' }%>
    <%else%>
        <%= f.select :status, options_for_select(feature_status_options,:selected => @bug.status), { prompt: 'Select status' }%>
   <%end%>
  </div>
  <%end%>


  <% if current_user.user_type == "qa" %>
  <div class="field">
   <label>Assigned To:</label>
         <div class="actions">
   <%= f.select(:assigned_to ,options_from_collection_for_select(@users,  :id, :name,:selected => @bug.assigned_to)) %>
  </div>
  </div>
  <% end %>
  
 

   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Show', @bug,{:style=>'color:#0000FF;font-size:20px'} %> ___
<%= link_to 'Back', bugs_path,{:style=>'color:#0000FF;font-size:20px'} %>
</div>

app/views/bugs/_form_qa.html.erb
<div class="signup">
<%= form_for(@bug) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :title, class: "control-label" %><br>
    <%= f.text_field :title, class: "form-control", :required => true   %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control", :required => true %>
  </div>

   <div class="field">
     <label>Project Name:</label><br>
      <%= @bug.project.project_name %>
  </div>

  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= image_tag(@bug.image.url, :style => "border: 1px solid grey;max-width:80px;") %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
	   <p>
	  <strong>Bug type:</strong>
	  <% if @bug.bug_type == "bug" %>
	    Bug
	  <%  else %>
	    Feature
	  <% end %>
	</p>
  </div>

<% if current_user.user_type != "manager" %>
  <div class="field">
    <%= f.label :status %><br>
    <% if @bug.status == nil || @bug.status == "" %>
    <%= "New"%>
		
   	<%else%>
    	 <%= @bug.status%>
   <%end%>
  </div>
  <%end%>


  <% if current_user.user_type == "qa" %>
  <div class="field">
   <label>Assigned To:</label>
         <div class="actions">
   <%= f.select(:assigned_to ,options_from_collection_for_select(@users,  :id, :name,:selected => @bug.assigned_to)) %>
  </div>
  </div>
  <% end %>
  
 

   <div class="actions">
    <%= f.submit "Update Bug" %>
  </div>
<% end %>
<%= link_to 'Show', @bug,{:style=>'color:#0000FF;font-size:20px'} %> ___
<%= link_to 'Back', bugs_path,{:style=>'color:#0000FF;font-size:20px'} %>
</div>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>
<% if current_user.user_type == "developer"%>
<%= render 'form_dev' %>
<%else%>
<%= render 'form_qa' %>
<%end%>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bugs</h1>
<%= will_paginate @projects, :page_links => false %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Project ID</th>
      <th>Deadline</th>
      <th>Image</th>
      <th>Bug type</th>
      <th>Status</th>
      <th>Assigned to</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
    <% if bug.status == "resolved" || bug.status == "completed" %>
      <tr class="success">
        <td><%= bug.title %></td>
        <td><%= bug.description %></td>
        <td><%= bug.project.project_name %></td>
        <td><%= bug.deadline %></td>
        <td><%= image_tag(bug.image.url, :style => "border: 1px solid grey;max-width:50px;") if bug.image.exists? %></td>

        <td><%= bug.bug_type %></td>

        <% if bug.status == nil || bug.status == "" %>
        <td><%= "New" %></td>
        <% else %>
        <td><%= bug.status %></td>
        <% end%>

        <td><%= bug.assigned_to %></td>
        <td><%= link_to 'Show', bug %></td>
        <% if current_user.user_type != "manager"%>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <%end%>
        <!-- <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    
      <% else %>

       <tr class="danger">
        <td><%= bug.title %></td>
        <td><%= bug.description %></td>
        <td><%= bug.project.project_name %></td>
        <td><%= bug.deadline %></td>
        <td><%= image_tag(bug.image.url, :style => "border: 1px solid grey;max-width:50px;border-radius:10px") if bug.image.exists? %></td>
        <td><%= bug.bug_type %></td>
       
        <% if bug.status == nil || bug.status == "" %>
        <td><%= "New" %></td>
        <% else %>
        <td><%= bug.status %></td>
        <% end%>
          <% if bug.assigned_to == nil %>
          <td>N/A</td>
          <% else %>
        <td><%= bug.assigned_to %></td>
        <% end %>
        <td><%= link_to 'Show', bug %></td>
        <% if current_user.user_type != "manager"%>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <%end%>
        <!-- <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>


<br>
<% if current_user.user_type != "developer"%>

<%= link_to 'Create New Bug', new_bug_path,{:style=>'color:#0000FF;font-size:20px'} %>

<%end%>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form' %>

app/views/bugs/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class = "bugshow">
 <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  <p class = "paraClass" >
  <strong>Title:</strong>
  <%= @bug.title %>
</p>

<p class = "paraClass">
  <strong>Description:</strong>
  <%= @bug.description %>
</p>

<p class = "paraClass">
  <strong>Project:</strong>
  <%= @bug.project_id %>
</p>

<p class = "paraClass">
  <strong>Deadline:</strong>
  <%= @bug.deadline %>
</p>

<p class = "paraClass">
  <strong>Image:</strong>
  <%= image_tag(@bug.image.url, :style => "border: 1px solid grey;max-width:80px;") if @bug.image.exists? %>
</p>

<p class = "paraClass">
  <strong>Bug type:</strong>
  <% if @bug.bug_type == "bug" %>
    Bug
  <%  else %>
    Feature
  <% end %>
</p>

<p class = "paraClass">
  <strong>Status:</strong>
  <% if @bug.status == nil %>
  <%= "New" %>
  <% else %>
  <%= @bug.status %>
  <% end %>
</p>

<p class = "paraClass">
  <strong>Assigned to:</strong>
  <% if @bug.assigned_to == nil %>
  <%= "N/A" %>
  <% else %>
  <%= @bug.assigned_to %>
  <% end %>
</p>


<%= link_to 'Back', bugs_path,{:style=>'color:#0000FF;font-size:20px'} %>
<% if current_user.user_type != "manager"%>
<%= link_to 'Edit', edit_bug_path(@bug),{:style=>'color:#0000FF;font-size:20px'} %>   
<%end%>
</div>