config/routes.rb
Rails.application.routes.draw do
  resources :bugs
  resources :projects
  resources :users
  resources :sessions
  root  'users#home'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new",  :as => "login"
  get "signup" => "users#new",   :as => "signup"
  match '/view_projects',         to: 'projects#view_projects', via: 'get'
  match '/view_developers',       to: 'users#view_developers', via: 'get'
  match '/view_qa_list',           to: 'users#view_qa_list', via: 'get'
  match '/details',                to: 'users#details', via: 'get'
  match '/view_qa_projects/:id',   to: 'users#view_qa_projects', 
  as:'view_qa_projects', via: 'get'

end

app/views/layouts/_header.html.erb
<nav style="height:120px" class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
          <img style="max-width:60px; margin-top: -7px;"
             src="/images.png">
             <span id="logo"> Bug Tracking System</span>
     </a>
    </div>
     <% if current_user %>
    <ul style="font-size: 20px" class="nav nav-tabs">


     <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Projects <span class="caret"></span></a>
        <ul class="dropdown-menu">

          <% if current_user.user_type== "manager" || current_user.user_type== "developer"  %>

            <li><a href="/projects">View all Projects</a></li>
            <%else%>
                   <li><%= link_to 'View Projects', view_qa_projects_path(current_user.id) %></li>
              <%end%> 
            <% if current_user.user_type== "manager" %>
              <li><%= link_to 'New Project', new_project_path %></li>
          <%end%>
        </ul>
      </li>


      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Bugs <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="/bugs">View all Bugs</a></li>

          <% if current_user.user_type== "manager" || current_user.user_type== "qa"  %>
              <li><%= link_to 'New Bug', new_bug_path %></li>
            <%end%>
        </ul>
      </li>


       <% if current_user.user_type== "manager" %>
      
      <!-- <li><a href="users/view_developers">Developors</a></li> -->
       <li><%= link_to 'Developors', view_developers_path %></li>
      <li><%= link_to 'QA', view_qa_list_path %></li>
      <% end %>
    </ul>
    <% end %>

        

<% if current_user %>
       <ul style="font-size: 15px;" class="nav navbar-nav navbar-right">
        <li style="color:#FFFFFF"><%= link_to "Manage Profile", current_user %></li>
        <li><%= link_to "Log out", logout_path %></li>
 </ul>
         <ul style="font-size: 15px;" class="nav navbar-nav navbar-right;">
       <li><%= image_tag(current_user.image.url, :style => "border: 1px solid grey;max-width:90px;border-radius:90%;float:navbar-right;") %></li>
        <li style="color:#FDFAFA";>Logged in as <%= current_user.name %>.</li>
       </ul>

        
      <% else %>
       <ul style="font-size: 15px;" class="nav navbar-nav navbar-right">
       <li style="margin-top: 30px"><a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="/sessions/new"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
     

    </ul>
     <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bug Tracking System</title>


	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>



	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header'%>
			
	<% flash.each do |type, message| %>
	  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible" role="alert">
	    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	    <%= message %>
	  </div>
	<% end %>
<%= yield %>

</body>
</html>

</html>